### ISSUE TITLE
GitHub上で自動テストしたい

### ISSUE THREAD

**Issue by Takatatsu9** [kitazawasyogo/bowling#6]
以下のコード？を`.github/workflows/dotnet4.yml`に配置してmergeすれば
以降はPRを追加・更新する度にテストが自動実行される、と思う。

```
name: .NET Framework 4.7.2

on: pull_request

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      run: msbuild $GITHUB_WORKSPACE

    - name: Run NUnit
      shell: cmd
      run: External-Bin\Net\2.0\nunit-console.exe Bowling.Test\bin\Debug\Bowling.Test.dll
```
